const BOT_UA_PATTERNS = [
  /googlebot/i,
  /google-inspectiontool/i,
  /google-safety/i,
  /googleother/i,
  /google-extended/i,
  /adsbot-google/i,
  /mediapartners-google/i,
  /feedfetcher-google/i,
  /apis-google/i,
  /bingbot/i,
  /slurp/i,
  /duckduckbot/i,
  /baiduspider/i,
  /yandexbot/i,
  /sogou/i,
  /facebookexternalhit/i,
  /twitterbot/i,
  /linkedinbot/i,
  /whatsapp/i,
  /telegrambot/i,
  /discordbot/i,
  /slackbot/i,
  /applebot/i,
  /semrushbot/i,
  /ahrefsbot/i,
  /mj12bot/i,
  /dotbot/i,
  /petalbot/i,
  /bytespider/i,
  /gptbot/i,
  /chatgpt-user/i,
  /claudebot/i,
  /anthropic-ai/i,
  /ccbot/i,
  /scrapy/i,
  /wget/i,
  /curl/i,
  /python-requests/i,
  /python-urllib/i,
  /go-http-client/i,
  /java\//i,
  /php\//i,
  /axios/i,
  /node-fetch/i,
  /headlesschrome/i,
  /phantomjs/i,
  /httrack/i,
  /crawler/i,
  /spider/i,
  /bot\//i,
  /bot;/i,
];

export function isBot(headers: Headers): boolean {
  const ua = headers.get("user-agent") ?? "";
  if (!ua) return true;
  return BOT_UA_PATTERNS.some((pattern) => pattern.test(ua));
}

const BOT_ISP_PATTERNS = [
  /google/i,
  /microsoft/i,
  /amazon/i,
  /facebook/i,
  /meta platforms/i,
  /twitter/i,
  /yandex/i,
  /baidu/i,
  /bytedance/i,
  /semrush/i,
  /ahrefs/i,
  /digitalocean/i,
  /hetzner/i,
  /ovh/i,
  /linode/i,
  /vultr/i,
  /oracle/i,
  /alibaba/i,
  /tencent/i,
];

export function isBotIsp(isp: string | undefined): boolean {
  if (!isp) return false;
  return BOT_ISP_PATTERNS.some((pattern) => pattern.test(isp));
}
